### ISSUE TITLE
Missing required dependencies on examples

### ISSUE THREAD

**Issue by lucasmenendez** [vocdoni/vocdoni-sdk#65]
**Context**
I'm trying to use the SDK (at least most of it) to test the census proof generation on anonymous voting. I'm doing this with the goal of check if the issue during the proof generation comes from the prover that we are using on the Go SDK or comes from the circom circuit or Arbo merkle tree.

**Issue description**
Reading the Developer Portal and trying to replicate almost the same code that the public example, I saw that the [ESM example](https://github.com/vocdoni/vocdoni-sdk/tree/main/examples/esm) did not specifies the [@ethersproject/wallet](https://www.npmjs.com/package/@ethersproject/wallet) as required dependecy, but it is used during the example.

I don't know if the example works without including that library in the [package.json](https://github.com/vocdoni/vocdoni-sdk/blob/main/examples/esm/package.json), and I don't know if it is really required there or if it is included in the SDK dependencies.

**Comment by marcvelmer** [comment]
Yes, it should be included.

BTW we are going to rebuild the dependencies in the examples, because the SDK dependency is directly the source code from the root. Therefore the SDK has to be built and because it has the [@ethersproject/wallet](https://www.npmjs.com/package/@ethersproject/wallet) dependency, it works. But again, this shouldn't be so and the plan is to have the examples working without needing the root source (the SDK)

FYI @elboletaire

**Comment by marcvelmer** [comment]
Fixed in #69
